apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cluster
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-manager
  ports:
    - name: cluster
      port: 1516
      targetPort: 1516