apiVersion: v1
kind: Secret
metadata:
  name: wazuh-auth
  namespace: { { .Release.Namespace } }
  labels:
    app: wazuh
    component: auth
type: Opaque
stringData:
  authd.pass: { { .Values.secrets.authdPassword | quote } }
