apiVersion: v1
kind: Secret
metadata:
  name: wazuh-cluster-secret
  namespace: { { .Release.Namespace } }
  labels:
    app: wazuh
    component: cluster
type: Opaque
stringData:
  cluster-key: { { .Values.secrets.clusterKey | quote } }
