apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cluster-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: cluster
type: Opaque
stringData:
  cluster-key: {{ .Values.secrets.clusterKey | quote }}
