apiVersion: v1
kind: Secret
metadata:
  name: wazuh-indexer-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh
    component: indexer
type: Opaque
stringData:
  username: {{ .Values.secrets.indexerUsername | quote }}
  password: {{ .Values.secrets.indexerPassword | quote }}
  hash: {{ .Values.secrets.indexerPasswordHash | quote }}