apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-manager-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: manager
type: Opaque
stringData:
  api-username: {{ .Values.secrets.apiUsername | quote }}
  api-password: {{ .Values.secrets.apiPassword | quote }}