apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-indexer-config
  namespace: {{ .Release.Namespace }}
data:
  opensearch.yml: |-
    network.host: "0.0.0.0"
    node.name: "${NODE_NAME}"
    cluster.name: "wazuh-cluster"


    cluster.initial_cluster_manager_nodes: 
      - "wazuh-indexer-0"
      {{- if gt (.Values.indexer.replicas | int) 1 }}
      - "wazuh-indexer-1"
      {{- end }}
      {{- if gt (.Values.indexer.replicas | int) 2 }}
      - "wazuh-indexer-2"
      {{- end }}
    
    discovery.seed_hosts:
      - "wazuh-indexer-0.wazuh-cluster.{{ .Release.Namespace }}.svc.cluster.local"
      {{- if gt (.Values.indexer.replicas | int) 1 }}
      - "wazuh-indexer-1.wazuh-cluster.{{ .Release.Namespace }}.svc.cluster.local"
      {{- end }}
      {{- if gt (.Values.indexer.replicas | int) 2 }}
      - "wazuh-indexer-2.wazuh-cluster.{{ .Release.Namespace }}.svc.cluster.local"
      {{- end }}
    
    path.data: /var/lib/wazuh-indexer
    path.logs: /var/log/wazuh-indexer
    
    http.port: 9200
    transport.port: 9300
    
    compatibility.override_main_response_version: true
    
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
    plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
    plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/config/certs/root-ca.pem
    
    plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
    plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/config/certs/root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.transport.resolve_hostname: false
    
    plugins.security.nodes_dn:
      - "CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
    plugins.security.authcz.admin_dn:
      - "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
    plugins.security.allow_default_init_securityindex: true
    
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]
    
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.enable_snapshot_restore_privilege: true
    
    cluster.routing.allocation.disk.threshold_enabled: false

  internal_users.yml: |-
    ---
    _meta:
      type: "internalusers"
      config_version: 2
    
    "{{ .Values.secrets.indexerUsername }}":
      hash:  "{{ .Values.secrets.indexerPasswordHash }}"
      reserved: true
      backend_roles:
        - "admin"
      description: "Admin user"
    
    "{{ .Values.secrets.dashboardUsername }}":
      hash: "{{ .Values.secrets.dashboardPasswordHash }}"
      reserved: true
      description: "Dashboard user"
