apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-indexer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-indexer
    node-type: index
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.indexer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.indexer.service.type }}
  selector:
    app: {{ .Release.Name }}-indexer
    node-type: index
  ports:
    - name: opensearch
      port: {{ .Values.indexer.service.port }}
      targetPort: http
      protocol: TCP