apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-manager-master
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager-master
    spec:      
      initContainers:
        - name: init-volumes
          image: wazuh/wazuh-manager:{{ .Values.wazuh.tag }}
          command:
            - /bin/sh
            - -c
            - |
              chown -R wazuh:wazuh /var/ossec/ || true
              mkdir -p /var/ossec/etc/shared/
              [ ! -f /var/ossec/etc/shared/ar.conf ] && echo "#clean" > /var/ossec/etc/shared/ar.conf || true
          volumeMounts:
            - name: wazuh-manager-master
              mountPath: /var/ossec/
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:{{ .Values.wazuh.tag }}
          env:
            - name: WAZUH_CLUSTER_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WAZUH_CLUSTER_NODE_TYPE
              value: "master"
            - name: WAZUH_CLUSTER_KEY
              value: "{{ .Values.secrets.clusterKey}}"
            - name: WAZUH_CLUSTER_NODES
              value: "wazuh-manager-master-0.wazuh-cluster.wazuh.svc.cluster.local"
            - name: INDEXER_URL
              value: https://wazuh-indexer.{{ .Release.Namespace }}.svc:9200
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-indexer-creds
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-indexer-creds
                  key: password
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: full
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /etc/ssl/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /etc/ssl/filebeat.pem
            - name: SSL_KEY
              value: /etc/ssl/filebeat.key
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-manager-secret
                  key: api-username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-manager-secret
                  key: api-password
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-master
              subPath: api/configuration
              mountPath: /var/ossec/api/configuration
            - name: wazuh-manager-master
              subPath: etc
              mountPath: /var/ossec/etc
            - name: wazuh-manager-master
              subPath: logs
              mountPath: /var/ossec/logs
            - name: wazuh-manager-master
              subPath: queue
              mountPath: /var/ossec/queue
            - name: wazuh-manager-master
              subPath: multigroups
              mountPath: /var/ossec/multigroups
            - name: wazuh-manager-master
              subPath: integrations
              mountPath: /var/ossec/integrations
            - name: wazuh-manager-master
              subPath: active-response/bin
              mountPath: /var/ossec/active-response/bin
            - name: wazuh-manager-master
              subPath: agentless
              mountPath: /var/ossec/agentless
            - name: wazuh-manager-master
              subPath: wodles
              mountPath: /var/ossec/wodles
            - name: wazuh-filebeat
              subPath: etc
              mountPath: /etc/filebeat
            - name: wazuh-filebeat
              subPath: var
              mountPath: /var/lib/filebeat
            - name: wazuh-manager
              mountPath: /etc/ssl/filebeat.key
              subPath: tls.key
              readOnly: true
            - name: wazuh-manager
              mountPath: /etc/ssl/filebeat.pem
              subPath: tls.crt
              readOnly: true
            - name: wazuh-root
              mountPath: /etc/ssl/root-ca.pem
              subPath: ca.crt
              readOnly: true
            - name: wazuh-auth
              mountPath: /var/ossec/etc/authd.pass
              subPath: authd.pass
              readOnly: true
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
      volumes:
        - name: wazuh-manager-master
          persistentVolumeClaim:
            claimName: wazuh-manager-master
        - name: wazuh-filebeat
          persistentVolumeClaim:
            claimName: wazuh-manager-filebeat
        - name: config
          configMap:
            name: wazuh-manager-master-conf
        - name: wazuh-manager
          secret:
            secretName: wazuh-manager
        - name: wazuh-root
          secret:
            secretName: wazuh-rootca-certificate
        - name: wazuh-auth
          secret:
            secretName: wazuh-auth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh-manager-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh-manager-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
