apiVersion: v1
kind: Service
metadata:
  name: wazuh
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh-manager
  annotations:
spec:
  type: NodePort
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: api
      port: 55000
      targetPort: 55000
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh-manager
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: ClusterIP
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: cluster
      port: 1516
      targetPort: 1516
    - name: api
      port: 55000
      targetPort: 55000
