# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh workers service: Agent reporting

apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh-manager
    # dns: route53
  annotations:
    # domainName: 'wazuh-manager.some-domain.com'  # TODO: Change this for a Hosted Zone you configured in AWS Route 53
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp

spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: wazuh-manager
spec:
  type: NodePort
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514