apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-workers
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-manager
    component: worker
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.manager.workers.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.manager.workers.service.type }}
  selector:
    app: {{ .Release.Name }}-manager
    node-type: worker
  ports:
    - name: agents-events
      port: {{ .Values.manager.workers.service.ports.agent }}
      targetPort: agents-events
      protocol: TCP
    - name: cluster
      port: {{ .Values.manager.workers.service.ports.cluster }}
      targetPort: cluster
      protocol: TCP